# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

title:            Daniel Luna
tagline:          'Software engineer'
description:      'Specialization is for insects. - Robert Heinlein'
url:              https://dcluna.github.io
baseurl:          "https://dcluna.github.io/"
author_gravatar:    39ffc379f09488e2378c587c6705978c # Gravatar md5 hash

author:
  name:           'Daniel Luna'
  url:            http://dcluna.github.io

gems: [jekyll-paginate, jekyll-feed, jekyll-gist]

paginate:         5
# Custom vars

github:
  repo:           https://www.github.com/dcluna

resume:
  url: https://www.dropbox.com/scl/fi/q53ptfpqoig92xkzvaskq/daniel-luna-resume.pdf?rlkey=sr3qe1gx5x64sluwjvzeir262&st=e7xbg0bv&dl=0

linkedin:
  url:  https://www.linkedin.com/in/dcluna

collections:
  - presentations
