# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

title:            Daniel Luna
tagline:          'Software engineer'
description:      'Specialization is for insects. - Robert Heinlein'
url:              http://dcluna.github.io
baseurl:          /
author_gravatar:    39ffc379f09488e2378c587c6705978c # Gravatar md5 hash

author:
  name:           'Daniel Luna'
  url:            http://dcluna.github.io

paginate:         5

# Custom vars

github:
  repo:           https://www.github.com/dcluna
