# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

title:            Daniel Luna
tagline:          'Software engineer'
description:      'Specialization is for insects. - Robert Heinlein'
url:              http://dcluna.github.io
baseurl:          "http://dcluna.github.io/"
author_gravatar:    39ffc379f09488e2378c587c6705978c # Gravatar md5 hash

author:
  name:           'Daniel Luna'
  url:            http://dcluna.github.io

gems: [jekyll-paginate, jekyll-feed, jekyll-gist]

paginate:         5
# Custom vars

github:
  repo:           https://www.github.com/dcluna

resume:
  url: https://www.dropbox.com/s/odaf4o969f46rrc/daniel-luna-resume.pdf?dl=0

linkedin:
  url:  https://www.linkedin.com/in/dcluna

collections:
  - presentations
